apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: docunex
spec:
  selector:
    matchLabels:
      app: angular
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: angular
    spec:
      containers:
        - name: docunex
          image: spandey00/docunex:2nd
          ports:
            - containerPort: 4200
---
# https://kubernetes.io/docs/concepts/services-networking/service/#defining-a-service
kind: Service
apiVersion: v1
metadata:
  name: docunex-service
spec:
  selector:
    app: angular
  ports:
    - protocol: TCP
      port: 4200
      targetPort: 4200
      nodePort: 31060
  type: NodePort
